language: node_js
node_js:
  - "node"

cache:
  directories:
    - "node_modules"

install: 
  - npm install
  - npm install karma-chrome-launcher
  - npm install karma-jasmine

script: npm run unit  
