language: node_js
node_js:
  - "node"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

cache:
  directories:
    - "node_modules"

install:
  - npm install
  - npm install karma-firefox-launcher --save-dev
  - npm install jasmine-core --save-dev
  - npm install karma-chrome-launcher --save-dev
  - npm install karma-jasmine --save-dev
  - npm install --global chrome-headless-launcher --save-dev


script: npm run unit
