language: node_js
node_js:
  - "node"

cache:
  directories:
    - "node_modules"

install: 
  - npm install
  - npm install jasmine-core --save-dev
  - npm install karma-chrome-launcher --save-dev
  - npm install karma-jasmine --save-dev

script: npm run unit  
